### ISSUE TITLE
Tester Rockside endpoint

### ISSUE THREAD

**Issue by stefdelec** [Arianee/arianeeJS#170]

**Comment by gnarco** [comment]
Brancher en dur le front du BDH pour gérer rockside
(fichier config.ts avec web3provider. Attention, web3Provider considere que le wallet qui signe est sur le noeud, il faut donc prévoir un hook/alternative. Ajouter le header apikey. Faire ce qu'il faut pour que le fichier de conf n'ai pas à contenir obligatoirement ces clefs).

Idem en back

Faire évoluer arianeeJS :
- Permettre de brancher une URL spécifique pour le web3provider
- Possibilité d'envoyer un header spécifique (pour injecter l'apiKey)

Faire évoluer wallet.ts (cloud function) :
- Utilisation de arianeeJS
- Capacité d'utiliser rockside (mais doit fonctionner dans les modes actuels)
