### ISSUE TITLE
address in issuer publicKey in owner

### ISSUE THREAD

**Issue by stefdelec** [Arianee/arianeeJS#202]
Method should return publicKey or Address? => où est ce que c'est utilisé pour éviter les regressions?

It should be address.
If publicKey => return both publicKey and address!

Or remove all public Key and make breaking change=> bump version to 2.0.0?

**Comment by gnarco** [comment]
je comprend pas la différence ?

**Comment by stefdelec** [comment]
Bhein des fois on return {publicKey:"zedze"}, et des fois { address:"zedze"

**Comment by gnarco** [comment]
on peut pas juste mettre les deux ?
