### ISSUE TITLE
On destroy remove addTokenAccess

### ISSUE THREAD

**Issue by stefdelec** [Arianee/arianeeJS#205]
When a certificate is destroyed 
And the certificate was never requested
Then user with certificateId and viewKey cannot request certificate

=> Today you can request certificate
=> should be not feasible

The red and blue Jazzicon is the "DEAD" public key.

![image.png](https://images.zenhubusercontent.com/5d9c41f9ecdcce0001979647/625a5ee4-dcf9-474d-b0ea-c04563bfcf4e)

**Comment by gnarco** [comment]
Tiens il est marrant ce bug
