### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by adwulfran** [Arianee/arianeeJS#217]
Hello,
I couldn't install arianee npm package. It looks like npm is not able to find websocket-node file.
After enter  `npm i --save @arianee/arianeejs`  I get following error :
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/WebSocket-Node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by mvaullerin** [comment]
Hello,

The right command to install the package is ``npm i --save @arianee/arianeejs``.
I suppose it's a typo in your message, but just to be sure...

What is your nodejs/npm version ?

**Comment by adwulfran** [comment]
Hello,
I mistyped in my message, but I used `npm i --save @arianee/arianeej` indeed.
My nodejs version is v12.14.1

**Comment by mvaullerin** [comment]
I just found a similar issue here :
https://stackoverflow.com/questions/53247394/npm-install-web3-install-fails-undefined-ls-remote

It seems that you don't have git installed properly or your path is not set correctly.

**Comment by adwulfran** [comment]
I installed it with git bash instead of windows powershell and it does work.
Thanks for your help
