### ISSUE TITLE
Fast KYB Process to create issuer identity to test createCertificate method

### ISSUE THREAD

**Issue by adwulfran** [Arianee/arianeeJS#227]
Hello,
In https://docs.arianee.org/docs/arianee-js-certificate I learned to create certificate with  `ArianeeWallets.methods.createCertificate(data)`. However  in data object you cannot pass parameter identity without going through KYB process.  Is there a way to do a fast KYB process to test createCertificate method ? It would be great to be allowed to pass in data object a  parameter to create issuer identity.  This will be only for development testing.

**Comment by gnarco** [comment]
Hi,

Identity is linked to certificate through issuer wallet.

You can't have a fast KYB process.

But, identity is not mandatory to issue a certificate.
In that case, the certificate won't be "authentic" as the issuer is not registered.

But it's fully functionnal, and you can even test the render with the Arianee Wallet app (ios/android).

Hope it helps
